### ISSUE TITLE
Lack shared library

### ISSUE THREAD

**Issue by cxumol** [kayac-chang/deno-jieba#1]
`deno --unstable run -A my.deno.js` was unable to run, and giving following error

```
Download https://deno.land/x/jieba@v1.0.0/target/debug/deno_jieba.dll
error: Uncaught (in promise) Error: Could not open library: The specified module could not be found.

  return Deno.dlopen(file, symbols);
              ^
    at Object.opSync (deno:core/01_core.js:170:12)
    at new DynamicLibrary (deno:ext/ffi/00_ffi.js:238:24)
    at Object.dlopen (deno:ext/ffi/00_ffi.js:323:12)
    at prepare (https://deno.land/x/jieba@v1.0.0/plug/plug.ts:111:15)
    at async https://deno.land/x/jieba@v1.0.0/bindings/bindings.ts:24:14
```

**Comment by kayac-chang** [comment]
Thank you for raising the issue ♥️.
This will be fixed by #2, in release v1.0.1.

Or you can try CDN which can import GitHub source code directly.
```ts
import { cut } from "https://cdn.jsdelivr.net/gh/kayac-chang/deno-jieba/mod.ts";

console.log(await cut("我來到北京清華大學"));
```

**Comment by cxumol** [comment]
Thank you for updates. However, this issue was not completed for me. Here are problems I have encountered in v1.0.1

1. the release of `v1.0.1` is missing on `https://deno.land/x/`

Then I tried 

```
import { cut } from "https://cdn.jsdelivr.net/gh/kayac-chang/deno-jieba/mod.ts";

console.log(await cut("我來到北京清華大學"));
```

and it returns

```
> deno --unstable run -A jieba.deno.js
Download https://cdn.jsdelivr.net/gh/kayac-chang/deno-jieba/mod.ts
Download https://cdn.jsdelivr.net/gh/kayac-chang/deno-jieba/bindings/bindings.ts
Download https://cdn.jsdelivr.net/gh/kayac-chang/deno-jieba/plug/plug.ts
Download https://cdn.jsdelivr.net/gh/kayac-chang/deno-jieba/plug/deps.ts
Download https://cdn.jsdelivr.net/gh/kayac-chang/deno-jieba/target/release/deno_jieba.dll
error: Uncaught (in promise) CacheError: Forbidden
    throw new CacheError(download.statusText);
          ^
    at protocolHttp (https://deno.land/x/cache@0.2.13/file_fetcher.ts:23:11)
    at async fetchFile (https://deno.land/x/cache@0.2.13/file_fetcher.ts:45:14)
    at async FileWrapper.fetch (https://deno.land/x/cache@0.2.13/file.ts:95:18)
    at async FileWrapper.get (https://deno.land/x/cache@0.2.13/file.ts:113:12)
    at async cache (https://deno.land/x/cache@0.2.13/cache.ts:67:10)
    at async Wrapper.cache (https://deno.land/x/cache@0.2.13/cache.ts:21:12)
    at async download (https://cdn.jsdelivr.net/gh/kayac-chang/deno-jieba/plug/plug.ts:101:16)
    at async prepare (https://cdn.jsdelivr.net/gh/kayac-chang/deno-jieba/plug/plug.ts:110:16)
    at async https://cdn.jsdelivr.net/gh/kayac-chang/deno-jieba/bindings/bindings.ts:24:14
```

That's because of 

2. https://cdn.jsdelivr.net/gh/kayac-chang/deno-jieba/target/release/deno_jieba.dll returns `403` saying 
`Package size exceeded the configured limit of 50 MB. Try https://github.com/kayac-chang/deno-jieba/tree/v1.0.1/target/release/deno_jieba.dll instead.`

3. it's weird because https://github.com/kayac-chang/deno-jieba/tree/v1.0.1/target/release/deno_jieba.dll gives `404`

The reason is that there is only MacOS build, but no Windows/Linux build. 

By the way, in release v1.0.1, I guess many files under `./release/**` are redundant and unnecessary to be included in git. Maybe `.dylib` `.so` `.dylib` are only necessary libs, although I don't have anything to support this point.

To my knowledge, I would suggest to use GitHub Actions (or some other CI which can run on different OS) to build the binary files of FFI libraries, and publish them into github release, so that `./release/**` can be ignored while allowing remote Deno users to download binary libraries.

**Comment by cxumol** [comment]
I learned that FFI plugin from Rust for Deno module have to be released per system (Windows/Linux/MacOS/etc.). But I'm not sure if system architecture (x86/x64/ARM/etc.) need to be concerned. 

To simplify cross-compiling problems, maybe compiling `jieba_rs` code as `.wasm` and let Deno call WebAssemply is a better idea.
